import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const countriesList = [
  { country_code: 'AF', country_name: 'Afghanistan', currency_symbol: '؋', currency_code: 'AFN', exchange_rate: 70.00 },
  { country_code: 'AL', country_name: 'Albania', currency_symbol: 'L', currency_code: 'ALL', exchange_rate: 90.00 },
  { country_code: 'DZ', country_name: 'Algeria', currency_symbol: 'د.ج', currency_code: 'DZD', exchange_rate: 130.00 },
  { country_code: 'AD', country_name: 'Andorra', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'AO', country_name: 'Angola', currency_symbol: 'Kz', currency_code: 'AOA', exchange_rate: 830.00 },
  { country_code: 'AG', country_name: 'Antigua and Barbuda', currency_symbol: 'EC$', currency_code: 'XCD', exchange_rate: 2.70 },
  { country_code: 'AR', country_name: 'Argentina', currency_symbol: '$', currency_code: 'ARS', exchange_rate: 800.00 },
  { country_code: 'AM', country_name: 'Armenia', currency_symbol: '֏', currency_code: 'AMD', exchange_rate: 400.00 },
  { country_code: 'AU', country_name: 'Australia', currency_symbol: '$', currency_code: 'AUD', exchange_rate: 1.50 },
  { country_code: 'AT', country_name: 'Austria', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'AZ', country_name: 'Azerbaijan', currency_symbol: '₼', currency_code: 'AZN', exchange_rate: 1.70 },
  { country_code: 'BS', country_name: 'Bahamas', currency_symbol: 'B$', currency_code: 'BSD', exchange_rate: 1.00 },
  { country_code: 'BH', country_name: 'Bahrain', currency_symbol: 'BD', currency_code: 'BHD', exchange_rate: 0.37 },
  { country_code: 'BD', country_name: 'Bangladesh', currency_symbol: '৳', currency_code: 'BDT', exchange_rate: 109.00 },
  { country_code: 'BB', country_name: 'Barbados', currency_symbol: 'Bds$', currency_code: 'BBD', exchange_rate: 2.00 },
  { country_code: 'BY', country_name: 'Belarus', currency_symbol: 'Br', currency_code: 'BYN', exchange_rate: 3.25 },
  { country_code: 'BE', country_name: 'Belgium', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'BZ', country_name: 'Belize', currency_symbol: 'BZ$', currency_code: 'BZD', exchange_rate: 2.00 },
  { country_code: 'BJ', country_name: 'Benin', currency_symbol: 'CFA', currency_code: 'XOF', exchange_rate: 600.00 },
  { country_code: 'BT', country_name: 'Bhutan', currency_symbol: 'Nu.', currency_code: 'BTN', exchange_rate: 83.00 },
  { country_code: 'BO', country_name: 'Bolivia', currency_symbol: 'Bs.', currency_code: 'BOB', exchange_rate: 6.90 },
  { country_code: 'BA', country_name: 'Bosnia and Herzegovina', currency_symbol: 'KM', currency_code: 'BAM', exchange_rate: 1.80 },
  { country_code: 'BW', country_name: 'Botswana', currency_symbol: 'P', currency_code: 'BWP', exchange_rate: 13.50 },
  { country_code: 'BR', country_name: 'Brazil', currency_symbol: 'R$', currency_code: 'BRL', exchange_rate: 5.00 },
  { country_code: 'BN', country_name: 'Brunei', currency_symbol: 'B$', currency_code: 'BND', exchange_rate: 1.34 },
  { country_code: 'BG', country_name: 'Bulgaria', currency_symbol: 'лв', currency_code: 'BGN', exchange_rate: 1.80 },
  { country_code: 'BF', country_name: 'Burkina Faso', currency_symbol: 'CFA', currency_code: 'XOF', exchange_rate: 600.00 },
  { country_code: 'BI', country_name: 'Burundi', currency_symbol: 'FBu', currency_code: 'BIF', exchange_rate: 2800.00 },
  { country_code: 'CV', country_name: 'Cabo Verde', currency_symbol: 'Esc', currency_code: 'CVE', exchange_rate: 102.00 },
  { country_code: 'KH', country_name: 'Cambodia', currency_symbol: '៛', currency_code: 'KHR', exchange_rate: 4100.00 },
  { country_code: 'CM', country_name: 'Cameroon', currency_symbol: 'FCFA', currency_code: 'XAF', exchange_rate: 600.00 },
  { country_code: 'CA', country_name: 'Canada', currency_symbol: '$', currency_code: 'CAD', exchange_rate: 1.35 },
  { country_code: 'CF', country_name: 'Central African Republic', currency_symbol: 'FCFA', currency_code: 'XAF', exchange_rate: 600.00 },
  { country_code: 'TD', country_name: 'Chad', currency_symbol: 'FCFA', currency_code: 'XAF', exchange_rate: 600.00 },
  { country_code: 'CL', country_name: 'Chile', currency_symbol: '$', currency_code: 'CLP', exchange_rate: 940.00 },
  { country_code: 'CN', country_name: 'China', currency_symbol: '¥', currency_code: 'CNY', exchange_rate: 7.20 },
  { country_code: 'CO', country_name: 'Colombia', currency_symbol: '$', currency_code: 'COP', exchange_rate: 3900.00 },
  { country_code: 'KM', country_name: 'Comoros', currency_symbol: 'CF', currency_code: 'KMF', exchange_rate: 450.00 },
  { country_code: 'CG', country_name: 'Congo', currency_symbol: 'FCFA', currency_code: 'XAF', exchange_rate: 600.00 },
  { country_code: 'CR', country_name: 'Costa Rica', currency_symbol: '₡', currency_code: 'CRC', exchange_rate: 510.00 },
  { country_code: 'CI', country_name: 'Côte d\'Ivoire', currency_symbol: 'CFA', currency_code: 'XOF', exchange_rate: 600.00 },
  { country_code: 'HR', country_name: 'Croatia', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'CU', country_name: 'Cuba', currency_symbol: '₱', currency_code: 'CUP', exchange_rate: 24.00 },
  { country_code: 'CY', country_name: 'Cyprus', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'CZ', country_name: 'Czech Republic', currency_symbol: 'Kč', currency_code: 'CZK', exchange_rate: 23.00 },
  { country_code: 'CD', country_name: 'Democratic Republic of the Congo', currency_symbol: 'FC', currency_code: 'CDF', exchange_rate: 2700.00 },
  { country_code: 'DK', country_name: 'Denmark', currency_symbol: 'kr', currency_code: 'DKK', exchange_rate: 6.80 },
  { country_code: 'DJ', country_name: 'Djibouti', currency_symbol: 'Fdj', currency_code: 'DJF', exchange_rate: 177.00 },
  { country_code: 'DM', country_name: 'Dominica', currency_symbol: 'EC$', currency_code: 'XCD', exchange_rate: 2.70 },
  { country_code: 'DO', country_name: 'Dominican Republic', currency_symbol: 'RD$', currency_code: 'DOP', exchange_rate: 58.00 },
  { country_code: 'EC', country_name: 'Ecuador', currency_symbol: '$', currency_code: 'USD', exchange_rate: 1.00 },
  { country_code: 'EG', country_name: 'Egypt', currency_symbol: 'E£', currency_code: 'EGP', exchange_rate: 47.00 },
  { country_code: 'SV', country_name: 'El Salvador', currency_symbol: '$', currency_code: 'USD', exchange_rate: 1.00 },
  { country_code: 'GQ', country_name: 'Equatorial Guinea', currency_symbol: 'FCFA', currency_code: 'XAF', exchange_rate: 600.00 },
  { country_code: 'ER', country_name: 'Eritrea', currency_symbol: 'Nfk', currency_code: 'ERN', exchange_rate: 15.00 },
  { country_code: 'EE', country_name: 'Estonia', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'SZ', country_name: 'Eswatini', currency_symbol: 'L', currency_code: 'SZL', exchange_rate: 19.00 },
  { country_code: 'ET', country_name: 'Ethiopia', currency_symbol: 'Br', currency_code: 'ETB', exchange_rate: 56.00 },
  { country_code: 'FJ', country_name: 'Fiji', currency_symbol: 'FJ$', currency_code: 'FJD', exchange_rate: 2.20 },
  { country_code: 'FI', country_name: 'Finland', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'FR', country_name: 'France', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'GA', country_name: 'Gabon', currency_symbol: 'FCFA', currency_code: 'XAF', exchange_rate: 600.00 },
  { country_code: 'GM', country_name: 'Gambia', currency_symbol: 'D', currency_code: 'GMD', exchange_rate: 67.00 },
  { country_code: 'GE', country_name: 'Georgia', currency_symbol: '₾', currency_code: 'GEL', exchange_rate: 2.70 },
  { country_code: 'DE', country_name: 'Germany', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'GH', country_name: 'Ghana', currency_symbol: 'GH₵', currency_code: 'GHS', exchange_rate: 13.00 },
  { country_code: 'GR', country_name: 'Greece', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'GD', country_name: 'Grenada', currency_symbol: 'EC$', currency_code: 'XCD', exchange_rate: 2.70 },
  { country_code: 'GT', country_name: 'Guatemala', currency_symbol: 'Q', currency_code: 'GTQ', exchange_rate: 7.80 },
  { country_code: 'GN', country_name: 'Guinea', currency_symbol: 'FG', currency_code: 'GNF', exchange_rate: 8600.00 },
  { country_code: 'GW', country_name: 'Guinea-Bissau', currency_symbol: 'CFA', currency_code: 'XOF', exchange_rate: 600.00 },
  { country_code: 'GY', country_name: 'Guyana', currency_symbol: 'G$', currency_code: 'GYD', exchange_rate: 210.00 },
  { country_code: 'HT', country_name: 'Haiti', currency_symbol: 'G', currency_code: 'HTG', exchange_rate: 130.00 },
  { country_code: 'HN', country_name: 'Honduras', currency_symbol: 'L', currency_code: 'HNL', exchange_rate: 24.70 },
  { country_code: 'HU', country_name: 'Hungary', currency_symbol: 'Ft', currency_code: 'HUF', exchange_rate: 360.00 },
  { country_code: 'IS', country_name: 'Iceland', currency_symbol: 'kr', currency_code: 'ISK', exchange_rate: 138.00 },
  { country_code: 'IN', country_name: 'India', currency_symbol: '₹', currency_code: 'INR', exchange_rate: 83.30 },
  { country_code: 'ID', country_name: 'Indonesia', currency_symbol: 'Rp', currency_code: 'IDR', exchange_rate: 15700.00 },
  { country_code: 'IR', country_name: 'Iran', currency_symbol: '﷼', currency_code: 'IRR', exchange_rate: 42000.00 },
  { country_code: 'IQ', country_name: 'Iraq', currency_symbol: 'د.ع', currency_code: 'IQD', exchange_rate: 1310.00 },
  { country_code: 'IE', country_name: 'Ireland', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'IL', country_name: 'Israel', currency_symbol: '₪', currency_code: 'ILS', exchange_rate: 3.65 },
  { country_code: 'IT', country_name: 'Italy', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'JM', country_name: 'Jamaica', currency_symbol: 'J$', currency_code: 'JMD', exchange_rate: 155.00 },
  { country_code: 'JP', country_name: 'Japan', currency_symbol: '¥', currency_code: 'JPY', exchange_rate: 151.00 },
  { country_code: 'JO', country_name: 'Jordan', currency_symbol: 'JD', currency_code: 'JOD', exchange_rate: 0.71 },
  { country_code: 'KZ', country_name: 'Kazakhstan', currency_symbol: '₸', currency_code: 'KZT', exchange_rate: 450.00 },
  { country_code: 'KE', country_name: 'Kenya', currency_symbol: 'KSh', currency_code: 'KES', exchange_rate: 132.00 },
  { country_code: 'KI', country_name: 'Kiribati', currency_symbol: '$', currency_code: 'AUD', exchange_rate: 1.50 },
  { country_code: 'KW', country_name: 'Kuwait', currency_symbol: 'KD', currency_code: 'KWD', exchange_rate: 0.31 },
  { country_code: 'KG', country_name: 'Kyrgyzstan', currency_symbol: 'сом', currency_code: 'KGS', exchange_rate: 89.00 },
  { country_code: 'LA', country_name: 'Laos', currency_symbol: '₭', currency_code: 'LAK', exchange_rate: 21000.00 },
  { country_code: 'LV', country_name: 'Latvia', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'LB', country_name: 'Lebanon', currency_symbol: 'L£', currency_code: 'LBP', exchange_rate: 89500.00 },
  { country_code: 'LS', country_name: 'Lesotho', currency_symbol: 'L', currency_code: 'LSL', exchange_rate: 19.00 },
  { country_code: 'LR', country_name: 'Liberia', currency_symbol: 'L$', currency_code: 'LRD', exchange_rate: 190.00 },
  { country_code: 'LY', country_name: 'Libya', currency_symbol: 'LD', currency_code: 'LYD', exchange_rate: 4.80 },
  { country_code: 'LI', country_name: 'Liechtenstein', currency_symbol: 'CHF', currency_code: 'CHF', exchange_rate: 0.90 },
  { country_code: 'LT', country_name: 'Lithuania', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'LU', country_name: 'Luxembourg', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'MG', country_name: 'Madagascar', currency_symbol: 'Ar', currency_code: 'MGA', exchange_rate: 4500.00 },
  { country_code: 'MW', country_name: 'Malawi', currency_symbol: 'MK', currency_code: 'MWK', exchange_rate: 1700.00 },
  { country_code: 'MY', country_name: 'Malaysia', currency_symbol: 'RM', currency_code: 'MYR', exchange_rate: 4.70 },
  { country_code: 'MV', country_name: 'Maldives', currency_symbol: 'Rf', currency_code: 'MVR', exchange_rate: 15.40 },
  { country_code: 'ML', country_name: 'Mali', currency_symbol: 'CFA', currency_code: 'XOF', exchange_rate: 600.00 },
  { country_code: 'MT', country_name: 'Malta', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'MH', country_name: 'Marshall Islands', currency_symbol: '$', currency_code: 'USD', exchange_rate: 1.00 },
  { country_code: 'MR', country_name: 'Mauritania', currency_symbol: 'UM', currency_code: 'MRU', exchange_rate: 39.50 },
  { country_code: 'MU', country_name: 'Mauritius', currency_symbol: '₨', currency_code: 'MUR', exchange_rate: 45.00 },
  { country_code: 'MX', country_name: 'Mexico', currency_symbol: '$', currency_code: 'MXN', exchange_rate: 16.50 },
  { country_code: 'FM', country_name: 'Micronesia', currency_symbol: '$', currency_code: 'USD', exchange_rate: 1.00 },
  { country_code: 'MD', country_name: 'Moldova', currency_symbol: 'L', currency_code: 'MDL', exchange_rate: 17.70 },
  { country_code: 'MC', country_name: 'Monaco', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'MN', country_name: 'Mongolia', currency_symbol: '₮', currency_code: 'MNT', exchange_rate: 3400.00 },
  { country_code: 'ME', country_name: 'Montenegro', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'MA', country_name: 'Morocco', currency_symbol: 'DH', currency_code: 'MAD', exchange_rate: 10.00 },
  { country_code: 'MZ', country_name: 'Mozambique', currency_symbol: 'MT', currency_code: 'MZN', exchange_rate: 64.00 },
  { country_code: 'MM', country_name: 'Myanmar', currency_symbol: 'K', currency_code: 'MMK', exchange_rate: 2100.00 },
  { country_code: 'NA', country_name: 'Namibia', currency_symbol: 'N$', currency_code: 'NAD', exchange_rate: 19.00 },
  { country_code: 'NR', country_name: 'Nauru', currency_symbol: '$', currency_code: 'AUD', exchange_rate: 1.50 },
  { country_code: 'NP', country_name: 'Nepal', currency_symbol: '₨', currency_code: 'NPR', exchange_rate: 133.00 },
  { country_code: 'NL', country_name: 'Netherlands', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'NZ', country_name: 'New Zealand', currency_symbol: '$', currency_code: 'NZD', exchange_rate: 1.65 },
  { country_code: 'NI', country_name: 'Nicaragua', currency_symbol: 'C$', currency_code: 'NIO', exchange_rate: 36.70 },
  { country_code: 'NE', country_name: 'Niger', currency_symbol: 'CFA', currency_code: 'XOF', exchange_rate: 600.00 },
  { country_code: 'NG', country_name: 'Nigeria', currency_symbol: '₦', currency_code: 'NGN', exchange_rate: 1500.00 },
  { country_code: 'KP', country_name: 'North Korea', currency_symbol: '₩', currency_code: 'KPW', exchange_rate: 900.00 },
  { country_code: 'MK', country_name: 'North Macedonia', currency_symbol: 'ден', currency_code: 'MKD', exchange_rate: 57.00 },
  { country_code: 'NO', country_name: 'Norway', currency_symbol: 'kr', currency_code: 'NOK', exchange_rate: 10.70 },
  { country_code: 'OM', country_name: 'Oman', currency_symbol: 'RO', currency_code: 'OMR', exchange_rate: 0.38 },
  { country_code: 'PK', country_name: 'Pakistan', currency_symbol: '₨', currency_code: 'PKR', exchange_rate: 278.00 },
  { country_code: 'PW', country_name: 'Palau', currency_symbol: '$', currency_code: 'USD', exchange_rate: 1.00 },
  { country_code: 'PS', country_name: 'Palestine', currency_symbol: '₪', currency_code: 'ILS', exchange_rate: 3.65 },
  { country_code: 'PA', country_name: 'Panama', currency_symbol: 'B/.', currency_code: 'PAB', exchange_rate: 1.00 },
  { country_code: 'PG', country_name: 'Papua New Guinea', currency_symbol: 'K', currency_code: 'PGK', exchange_rate: 3.80 },
  { country_code: 'PY', country_name: 'Paraguay', currency_symbol: '₲', currency_code: 'PYG', exchange_rate: 7300.00 },
  { country_code: 'PE', country_name: 'Peru', currency_symbol: 'S/.', currency_code: 'PEN', exchange_rate: 3.70 },
  { country_code: 'PH', country_name: 'Philippines', currency_symbol: '₱', currency_code: 'PHP', exchange_rate: 56.20 },
  { country_code: 'PL', country_name: 'Poland', currency_symbol: 'zł', currency_code: 'PLN', exchange_rate: 4.00 },
  { country_code: 'PT', country_name: 'Portugal', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'QA', country_name: 'Qatar', currency_symbol: 'QR', currency_code: 'QAR', exchange_rate: 3.64 },
  { country_code: 'RO', country_name: 'Romania', currency_symbol: 'lei', currency_code: 'RON', exchange_rate: 4.60 },
  { country_code: 'RU', country_name: 'Russia', currency_symbol: '₽', currency_code: 'RUB', exchange_rate: 92.50 },
  { country_code: 'RW', country_name: 'Rwanda', currency_symbol: 'FRw', currency_code: 'RWF', exchange_rate: 1280.00 },
  { country_code: 'KN', country_name: 'Saint Kitts and Nevis', currency_symbol: 'EC$', currency_code: 'XCD', exchange_rate: 2.70 },
  { country_code: 'LC', country_name: 'Saint Lucia', currency_symbol: 'EC$', currency_code: 'XCD', exchange_rate: 2.70 },
  { country_code: 'VC', country_name: 'Saint Vincent and the Grenadines', currency_symbol: 'EC$', currency_code: 'XCD', exchange_rate: 2.70 },
  { country_code: 'WS', country_name: 'Samoa', currency_symbol: 'SAT', currency_code: 'WST', exchange_rate: 2.75 },
  { country_code: 'SM', country_name: 'San Marino', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'ST', country_name: 'Sao Tome and Principe', currency_symbol: 'Db', currency_code: 'STN', exchange_rate: 22.50 },
  { country_code: 'SA', country_name: 'Saudi Arabia', currency_symbol: 'SR', currency_code: 'SAR', exchange_rate: 3.75 },
  { country_code: 'SN', country_name: 'Senegal', currency_symbol: 'CFA', currency_code: 'XOF', exchange_rate: 600.00 },
  { country_code: 'RS', country_name: 'Serbia', currency_symbol: 'RSD', currency_code: 'RSD', exchange_rate: 108.00 },
  { country_code: 'SC', country_name: 'Seychelles', currency_symbol: 'SR', currency_code: 'SCR', exchange_rate: 13.50 },
  { country_code: 'SL', country_name: 'Sierra Leone', currency_symbol: 'Le', currency_code: 'SLE', exchange_rate: 22.50 },
  { country_code: 'SG', country_name: 'Singapore', currency_symbol: 'S$', currency_code: 'SGD', exchange_rate: 1.35 },
  { country_code: 'SK', country_name: 'Slovakia', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'SI', country_name: 'Slovenia', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'SB', country_name: 'Solomon Islands', currency_symbol: 'SI$', currency_code: 'SBD', exchange_rate: 8.50 },
  { country_code: 'SO', country_name: 'Somalia', currency_symbol: 'Sh.So.', currency_code: 'SOS', exchange_rate: 570.00 },
  { country_code: 'ZA', country_name: 'South Africa', currency_symbol: 'R', currency_code: 'ZAR', exchange_rate: 19.00 },
  { country_code: 'KR', country_name: 'South Korea', currency_symbol: '₩', currency_code: 'KRW', exchange_rate: 1350.00 },
  { country_code: 'SS', country_name: 'South Sudan', currency_symbol: 'SSP', currency_code: 'SSP', exchange_rate: 1000.00 },
  { country_code: 'ES', country_name: 'Spain', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'LK', country_name: 'Sri Lanka', currency_symbol: 'Rs', currency_code: 'LKR', exchange_rate: 300.00 },
  { country_code: 'SD', country_name: 'Sudan', currency_symbol: 'SD', currency_code: 'SDG', exchange_rate: 600.00 },
  { country_code: 'SR', country_name: 'Suriname', currency_symbol: 'SRD', currency_code: 'SRD', exchange_rate: 34.00 },
  { country_code: 'SE', country_name: 'Sweden', currency_symbol: 'kr', currency_code: 'SEK', exchange_rate: 10.80 },
  { country_code: 'CH', country_name: 'Switzerland', currency_symbol: 'CHF', currency_code: 'CHF', exchange_rate: 0.90 },
  { country_code: 'SY', country_name: 'Syria', currency_symbol: 'LS', currency_code: 'SYP', exchange_rate: 13000.00 },
  { country_code: 'TJ', country_name: 'Tajikistan', currency_symbol: 'SM', currency_code: 'TJS', exchange_rate: 10.90 },
  { country_code: 'TZ', country_name: 'Tanzania', currency_symbol: 'TSh', currency_code: 'TZS', exchange_rate: 2570.00 },
  { country_code: 'TH', country_name: 'Thailand', currency_symbol: '฿', currency_code: 'THB', exchange_rate: 36.50 },
  { country_code: 'TL', country_name: 'Timor-Leste', currency_symbol: '$', currency_code: 'USD', exchange_rate: 1.00 },
  { country_code: 'TG', country_name: 'Togo', currency_symbol: 'CFA', currency_code: 'XOF', exchange_rate: 600.00 },
  { country_code: 'TO', country_name: 'Tonga', currency_symbol: 'T$', currency_code: 'TOP', exchange_rate: 2.35 },
  { country_code: 'TT', country_name: 'Trinidad and Tobago', currency_symbol: 'TT$', currency_code: 'TTD', exchange_rate: 6.80 },
  { country_code: 'TN', country_name: 'Tunisia', currency_symbol: 'DT', currency_code: 'TND', exchange_rate: 3.10 },
  { country_code: 'TR', country_name: 'Türkiye', currency_symbol: '₺', currency_code: 'TRY', exchange_rate: 32.00 },
  { country_code: 'TM', country_name: 'Turkmenistan', currency_symbol: 'TMT', currency_code: 'TMT', exchange_rate: 3.50 },
  { country_code: 'TV', country_name: 'Tuvalu', currency_symbol: '$', currency_code: 'AUD', exchange_rate: 1.50 },
  { country_code: 'UG', country_name: 'Uganda', currency_symbol: 'USh', currency_code: 'UGX', exchange_rate: 3800.00 },
  { country_code: 'UA', country_name: 'Ukraine', currency_symbol: '₴', currency_code: 'UAH', exchange_rate: 39.00 },
  { country_code: 'AE', country_name: 'United Arab Emirates', currency_symbol: 'د.إ', currency_code: 'AED', exchange_rate: 3.67 },
  { country_code: 'GB', country_name: 'United Kingdom', currency_symbol: '£', currency_code: 'GBP', exchange_rate: 0.79 },
  { country_code: 'US', country_name: 'United States', currency_symbol: '$', currency_code: 'USD', exchange_rate: 1.00 },
  { country_code: 'UY', country_name: 'Uruguay', currency_symbol: '$U', currency_code: 'UYU', exchange_rate: 38.50 },
  { country_code: 'UZ', country_name: 'Uzbekistan', currency_symbol: 'soum', currency_code: 'UZS', exchange_rate: 12500.00 },
  { country_code: 'VU', country_name: 'Vanuatu', currency_symbol: 'VT', currency_code: 'VUV', exchange_rate: 120.00 },
  { country_code: 'VA', country_name: 'Vatican City', currency_symbol: '€', currency_code: 'EUR', exchange_rate: 0.92 },
  { country_code: 'VE', country_name: 'Venezuela', currency_symbol: 'Bs.S', currency_code: 'VES', exchange_rate: 36.30 },
  { country_code: 'VN', country_name: 'Vietnam', currency_symbol: '₫', currency_code: 'VND', exchange_rate: 25000.00 },
  { country_code: 'YE', country_name: 'Yemen', currency_symbol: 'YR', currency_code: 'YER', exchange_rate: 250.00 },
  { country_code: 'ZM', country_name: 'Zambia', currency_symbol: 'ZK', currency_code: 'ZMW', exchange_rate: 25.00 },
  { country_code: 'ZW', country_name: 'Zimbabwe', currency_symbol: 'ZiG', currency_code: 'ZWG', exchange_rate: 13.50 },
];

async function main() {
  console.log('Populating countries...');
  for (const c of countriesList) {
    await prisma.countries.upsert({
      where: { country_code: c.country_code },
      update: {
        country_name: c.country_name,
        currency_symbol: c.currency_symbol,
        currency_code: c.currency_code,
        exchange_rate: c.exchange_rate,
        auto_update: c.country_code !== 'US',
      },
      create: {
        ...c,
        auto_update: c.country_code !== 'US',
      },
    });
  }
  console.log('All 195 countries populated successfully!');
}

main()
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
